class InternalError(Exception):
    pass


class UserError(Exception):
    pass
